/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bcsfll.uht.ui;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bcsfll.uht.ui.utiliy.ClipboardUtil;
import org.bcsfll.uht.ui.utiliy.OpenHomePageUtil;
import org.bcsfll.uht.ui.utiliy.PropertiesUtil;
import org.bcsfll.uht.utiliy.DateUtil;
import org.bcsfll.uht.utiliy.FileUtil;
import org.bcsfll.uht.utiliy.NetUtil;
import org.bcsfll.uht.utiliy.OSUtil;

/**
 *
 * @author tone
 */
public class HostsTool extends javax.swing.JFrame {

    /**
     * Creates new form HostsTool
     */
    private static boolean THINKS_TYPEB = true;
    private static boolean LICENSE_TYPEB = true;

    public HostsTool() {
        initComponents();
        // this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/logo.png"); // NOI18N
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/org/bcsfll/uht/ui/resources/logo.png")));
        this.setLocationRelativeTo(null);
        FileChooser_Save.setApproveButtonText("保存hosts");
        /**
         *
         */
        PropertiesUtil propertiesUtil = PropertiesUtil.getInstance(this.getClass().getResourceAsStream("/org/bcsfll/uht/ui/resources/about.properties"));

        Label_About.setText(propertiesUtil.getValueByKey("desc"));
        Label_Mail.setText(propertiesUtil.getValueByKey("mail"));
        Label_HomePage.setText(propertiesUtil.getValueByKey("homepage"));
        Label_WARA.setText(propertiesUtil.getValueByKey("wara"));

        this.setTitle("HostsTool_" + propertiesUtil.getValueByKey("version"));
        TextArea_Help.setText(propertiesUtil.getValueByKey("info"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dialog_About = new javax.swing.JDialog();
        Panel_About = new javax.swing.JPanel();
        Panel_Info = new javax.swing.JPanel();
        Label_Version = new javax.swing.JLabel();
        Label_About = new javax.swing.JLabel();
        Label_WARA = new javax.swing.JLabel();
        Label_Auther = new javax.swing.JLabel();
        Label_Mail = new javax.swing.JLabel();
        Label_HomePage = new javax.swing.JLabel();
        Label_CopyRight = new javax.swing.JLabel();
        Panel_Help = new javax.swing.JPanel();
        ScrollPane_Help = new javax.swing.JScrollPane();
        TextArea_Help = new javax.swing.JTextArea();
        Label_Help = new javax.swing.JLabel();
        Panel_License = new javax.swing.JPanel();
        ScrollPane_License = new javax.swing.JScrollPane();
        TextArea_License = new javax.swing.JTextArea();
        Label_License = new javax.swing.JLabel();
        ToggleButton_Thinks = new javax.swing.JToggleButton();
        ToggleButton_License = new javax.swing.JToggleButton();
        Label_Logo = new javax.swing.JLabel();
        Label_Desc = new javax.swing.JLabel();
        FileChooser_Save = new javax.swing.JFileChooser();
        PopupMenu_CopyMail = new javax.swing.JPopupMenu();
        MenuItem_CopyMail = new javax.swing.JMenuItem();
        PopupMenu_Open = new javax.swing.JPopupMenu();
        MenuItem_Open = new javax.swing.JMenuItem();
        TabbedPane = new javax.swing.JTabbedPane();
        Panel_Local = new javax.swing.JPanel();
        Button_View = new javax.swing.JButton();
        ScrollPane_Local = new javax.swing.JScrollPane();
        TextArea_Local = new javax.swing.JTextArea();
        Panel_Net = new javax.swing.JPanel();
        Button_Get = new javax.swing.JButton();
        ScrollPane_Net = new javax.swing.JScrollPane();
        TextArea_Net = new javax.swing.JTextArea();
        Button_Update = new javax.swing.JButton();
        Panel_Params = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        Button_Save = new javax.swing.JButton();
        Panel_Bak = new javax.swing.JPanel();
        ScrollPane_Bak_Table = new javax.swing.JScrollPane();
        Table_Bak = new javax.swing.JTable();
        Button_Bak_View = new javax.swing.JButton();
        ScrollPane_Bak_TextArea = new javax.swing.JScrollPane();
        TextArea_Bak = new javax.swing.JTextArea();
        Button_Bak = new javax.swing.JButton();
        Button_Bak_Update = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Menu_Tool = new javax.swing.JMenu();
        MenuItem_DNS = new javax.swing.JMenuItem();
        Menu = new javax.swing.JMenu();
        MenuItem = new javax.swing.JMenuItem();

        Dialog_About.setResizable(false);

        Panel_About.setBorder(null);
        Panel_About.setLayout(new java.awt.CardLayout());

        Label_Version.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Version.setText("V1.0.1");

        Label_About.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_About.setText("HostsTool是Java编写的在线Hosts获取工具");

        Label_WARA.setForeground(java.awt.Color.red);
        Label_WARA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_WARA.setText("本程序无任何担保,请使用前做好相关文件备份工作");

        Label_Auther.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Auther.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/ah.png"))); // NOI18N

        Label_Mail.setForeground(java.awt.Color.green);
        Label_Mail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Mail.setText("bcsflilong@yeah.net");
        Label_Mail.setToolTipText("作者Email，右键可复制");
        Label_Mail.setComponentPopupMenu(PopupMenu_CopyMail);
        Label_Mail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_MailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_MailMouseExited(evt);
            }
        });

        Label_HomePage.setForeground(java.awt.Color.cyan);
        Label_HomePage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_HomePage.setText("http://www.cnblogs.com/bcsflilong/");
        Label_HomePage.setToolTipText("作者博客主页，右键可打开");
        Label_HomePage.setComponentPopupMenu(PopupMenu_Open);
        Label_HomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Label_HomePageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Label_HomePageMouseExited(evt);
            }
        });

        Label_CopyRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_CopyRight.setText("Copyright © 2014-2016 bcsfll");

        javax.swing.GroupLayout Panel_InfoLayout = new javax.swing.GroupLayout(Panel_Info);
        Panel_Info.setLayout(Panel_InfoLayout);
        Panel_InfoLayout.setHorizontalGroup(
            Panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Label_WARA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addGroup(Panel_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Label_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Auther, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Mail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_HomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_CopyRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_InfoLayout.setVerticalGroup(
            Panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InfoLayout.createSequentialGroup()
                .addComponent(Label_Version)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_About)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Auther)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_CopyRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Mail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_HomePage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_WARA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Panel_About.add(Panel_Info, "card2");

        TextArea_Help.setEditable(false);
        TextArea_Help.setColumns(20);
        TextArea_Help.setLineWrap(true);
        TextArea_Help.setRows(5);
        TextArea_Help.setText("           \n          只要GFW一天不倒，我们就要努力！\n\n          本软件的开发是在Ubuntu14.04.1 下使用Oracle JDK1.6_45进行的开发，所以建议使用者也使用JDK1.6及以上版本运行本程序。因为没有Windows机器，所以没有测试。\n\n          另外请以sudo java -jar 这种方式运行本程序，否则本程序将无法更新和备份本机的Hosts文件。\n\n         后续将新增刷新本机DNS和重启网络服务的功能，另外将对获取网络上的Hosts文件这一功能进行改进，避免出现卡顿的现象。\n\n         另外本程序应该是涉嫌盗链了，但是也没有办法，以后改吧         ");
        ScrollPane_Help.setViewportView(TextArea_Help);

        Label_Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Help.setText("使用帮助及更新说明");

        javax.swing.GroupLayout Panel_HelpLayout = new javax.swing.GroupLayout(Panel_Help);
        Panel_Help.setLayout(Panel_HelpLayout);
        Panel_HelpLayout.setHorizontalGroup(
            Panel_HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Label_Help, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ScrollPane_Help, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        Panel_HelpLayout.setVerticalGroup(
            Panel_HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_HelpLayout.createSequentialGroup()
                .addComponent(Label_Help)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Help, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
        );

        Panel_About.add(Panel_Help, "card3");

        TextArea_License.setColumns(20);
        TextArea_License.setLineWrap(true);
        TextArea_License.setRows(5);
        TextArea_License.setText("此软件为自由软件，您可以在自由软件基金会发布的GNU通用许可证的条款下进行修改或再发布；\n许可协议可以是第三版，或之后的任何新版本。\n  \n发布本程序是希望给您带来便利，但不做任何担保，甚至没有适销性或特定目的而隐含的担保。\n有关详细信息，请参阅GNU通用许可证。\n  \n您应该随本程序收到了一份GNU通用许可证；如果没有，可写一份信向自由软件基金会索取。\nFoundation, Inc., 51 Franklin Street, Fifth Floor, Boston,\nMA 02110-1301, USA.");
        ScrollPane_License.setViewportView(TextArea_License);

        Label_License.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_License.setText("许可协议");

        javax.swing.GroupLayout Panel_LicenseLayout = new javax.swing.GroupLayout(Panel_License);
        Panel_License.setLayout(Panel_LicenseLayout);
        Panel_LicenseLayout.setHorizontalGroup(
            Panel_LicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane_License, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
            .addComponent(Label_License, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_LicenseLayout.setVerticalGroup(
            Panel_LicenseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_LicenseLayout.createSequentialGroup()
                .addComponent(Label_License)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_License, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
        );

        Panel_About.add(Panel_License, "card4");

        ToggleButton_Thinks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/help-about.png"))); // NOI18N
        ToggleButton_Thinks.setText("帮助");
        ToggleButton_Thinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_ThinksActionPerformed(evt);
            }
        });

        ToggleButton_License.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/license.png"))); // NOI18N
        ToggleButton_License.setText("许可");
        ToggleButton_License.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_LicenseActionPerformed(evt);
            }
        });

        Label_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/logo.png"))); // NOI18N

        Label_Desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Desc.setText("Hosts文件修改工具");

        javax.swing.GroupLayout Dialog_AboutLayout = new javax.swing.GroupLayout(Dialog_About.getContentPane());
        Dialog_About.getContentPane().setLayout(Dialog_AboutLayout);
        Dialog_AboutLayout.setHorizontalGroup(
            Dialog_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Dialog_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Dialog_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel_About, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Dialog_AboutLayout.createSequentialGroup()
                        .addComponent(ToggleButton_Thinks, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ToggleButton_License, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Label_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Dialog_AboutLayout.setVerticalGroup(
            Dialog_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Dialog_AboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_Desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_About, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Dialog_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ToggleButton_Thinks)
                    .addComponent(ToggleButton_License))
                .addContainerGap())
        );

        FileChooser_Save.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        FileChooser_Save.setDialogTitle("保存Hosts");
        FileChooser_Save.setSelectedFile(new java.io.File("/home/tone/hosts"));

        MenuItem_CopyMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/editcopy.png"))); // NOI18N
        MenuItem_CopyMail.setText("复制作者Email");
        MenuItem_CopyMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_CopyMailActionPerformed(evt);
            }
        });
        PopupMenu_CopyMail.add(MenuItem_CopyMail);

        MenuItem_Open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/browser.png"))); // NOI18N
        MenuItem_Open.setText("访问作者博客主页");
        MenuItem_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_OpenActionPerformed(evt);
            }
        });
        PopupMenu_Open.add(MenuItem_Open);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HostsTool_V1.0.1");

        TabbedPane.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        Button_View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/logviewer.png"))); // NOI18N
        Button_View.setText("查看本机HOSTS");
        Button_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ViewActionPerformed(evt);
            }
        });

        TextArea_Local.setEditable(false);
        TextArea_Local.setColumns(20);
        TextArea_Local.setRows(5);
        ScrollPane_Local.setViewportView(TextArea_Local);

        javax.swing.GroupLayout Panel_LocalLayout = new javax.swing.GroupLayout(Panel_Local);
        Panel_Local.setLayout(Panel_LocalLayout);
        Panel_LocalLayout.setHorizontalGroup(
            Panel_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LocalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPane_Local, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_LocalLayout.setVerticalGroup(
            Panel_LocalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_LocalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_View)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Local, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPane.addTab("本机HOSTS", Panel_Local);

        Button_Get.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/download.png"))); // NOI18N
        Button_Get.setText("获取HOSTS");
        Button_Get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_GetActionPerformed(evt);
            }
        });

        TextArea_Net.setColumns(20);
        TextArea_Net.setRows(5);
        ScrollPane_Net.setViewportView(TextArea_Net);

        Button_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/update.png"))); // NOI18N
        Button_Update.setText("更新本机HOSTS");
        Button_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_UpdateActionPerformed(evt);
            }
        });

        Panel_Params.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jCheckBox1.setText("localhost 部分");
        Panel_Params.add(jCheckBox1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/local.png"))); // NOI18N
        Panel_Params.add(jLabel1);

        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Google");
        Panel_Params.add(jCheckBox2);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/google.png"))); // NOI18N
        Panel_Params.add(jLabel2);

        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Wiki");
        Panel_Params.add(jCheckBox3);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/wikipedia.png"))); // NOI18N
        Panel_Params.add(jLabel3);

        jCheckBox4.setSelected(true);
        jCheckBox4.setText("FaceBook");
        Panel_Params.add(jCheckBox4);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/facebook.png"))); // NOI18N
        Panel_Params.add(jLabel4);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Twitter");
        Panel_Params.add(jCheckBox5);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/twitter.png"))); // NOI18N
        Panel_Params.add(jLabel5);

        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Filckr");
        Panel_Params.add(jCheckBox6);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/flickr.png"))); // NOI18N
        Panel_Params.add(jLabel6);

        jCheckBox7.setSelected(true);
        jCheckBox7.setText("Dropbox");
        Panel_Params.add(jCheckBox7);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/dropbox.png"))); // NOI18N
        Panel_Params.add(jLabel7);

        jCheckBox8.setSelected(true);
        jCheckBox8.setText("0neDrive");
        Panel_Params.add(jCheckBox8);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/im-msn.png"))); // NOI18N
        Panel_Params.add(jLabel8);

        jCheckBox9.setSelected(true);
        jCheckBox9.setText("Youtube");
        Panel_Params.add(jCheckBox9);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/youtube.png"))); // NOI18N
        Panel_Params.add(jLabel9);

        Button_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/save.png"))); // NOI18N
        Button_Save.setText(" 保存Hosts文件到本地");
        Button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_NetLayout = new javax.swing.GroupLayout(Panel_Net);
        Panel_Net.setLayout(Panel_NetLayout);
        Panel_NetLayout.setHorizontalGroup(
            Panel_NetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_NetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Get, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPane_Net)
                    .addComponent(Button_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Params, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_NetLayout.setVerticalGroup(
            Panel_NetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Params, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Get)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Net, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Save)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Update)
                .addContainerGap())
        );

        TabbedPane.addTab("网络HOSTS", Panel_Net);

        Table_Bak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "备份文件列表"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_Bak.setColumnSelectionAllowed(true);
        Table_Bak.setRowHeight(28);
        Table_Bak.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ScrollPane_Bak_Table.setViewportView(Table_Bak);
        Table_Bak.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Table_Bak.getColumnModel().getColumn(0).setResizable(false);

        Button_Bak_View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/editor.png"))); // NOI18N
        Button_Bak_View.setText("查看选中HOSTS");
        Button_Bak_View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Bak_ViewActionPerformed(evt);
            }
        });

        TextArea_Bak.setEditable(false);
        TextArea_Bak.setColumns(20);
        TextArea_Bak.setRows(5);
        ScrollPane_Bak_TextArea.setViewportView(TextArea_Bak);

        Button_Bak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/deja-dup.png"))); // NOI18N
        Button_Bak.setText("还原HOSTS");
        Button_Bak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_BakActionPerformed(evt);
            }
        });

        Button_Bak_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/eog.png"))); // NOI18N
        Button_Bak_Update.setText("刷新备份文件列表");
        Button_Bak_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Bak_UpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_BakLayout = new javax.swing.GroupLayout(Panel_Bak);
        Panel_Bak.setLayout(Panel_BakLayout);
        Panel_BakLayout.setHorizontalGroup(
            Panel_BakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_BakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane_Bak_Table, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                    .addComponent(Button_Bak_View, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollPane_Bak_TextArea)
                    .addComponent(Button_Bak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_Bak_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_BakLayout.setVerticalGroup(
            Panel_BakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_BakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Button_Bak_Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Bak_Table, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Bak_View)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPane_Bak_TextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Bak)
                .addContainerGap())
        );

        TabbedPane.addTab("还原HOSTS", Panel_Bak);

        Menu_Tool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/tool.png"))); // NOI18N
        Menu_Tool.setText("工具");

        MenuItem_DNS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/restart.png"))); // NOI18N
        MenuItem_DNS.setText("刷新缓存使hosts生效");
        MenuItem_DNS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_DNSActionPerformed(evt);
            }
        });
        Menu_Tool.add(MenuItem_DNS);

        MenuBar.add(Menu_Tool);

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/help.png"))); // NOI18N
        Menu.setText("帮助");

        MenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bcsfll/uht/ui/resources/about.png"))); // NOI18N
        MenuItem.setText("关于");
        MenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemActionPerformed(evt);
            }
        });
        Menu.add(MenuItem);

        MenuBar.add(Menu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ViewActionPerformed
        Thread thread = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    // TODO add your handling code here:
                    String hostPathName = OSUtil.getInstance().getHostsFilePathName();
                    String localHost = FileUtil.readFile(hostPathName);
                    TextArea_Local.setText(localHost);
                } catch (Exception ex) {
                    //Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        thread.start();

    }//GEN-LAST:event_Button_ViewActionPerformed

    private void Button_Bak_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Bak_UpdateActionPerformed
        try {
            // TODO add your handling code here:
            String hostPathName = OSUtil.getInstance().getHostsFilePath();
            ArrayList<String> filePathNameList = FileUtil.getFileList(hostPathName, true);

            DefaultTableModel tableModel = (DefaultTableModel) Table_Bak.getModel();
            tableModel.setRowCount(0);
            for (String filePathName : filePathNameList) {
                tableModel.addRow(new Object[]{filePathName});
            }
            TextArea_Bak.setText(null);
        } catch (Exception ex) {
            //Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Button_Bak_UpdateActionPerformed

    private void Button_Bak_ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Bak_ViewActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel tableModel = (DefaultTableModel) Table_Bak.getModel();
            int[] indexs = Table_Bak.getSelectedRows();
            if (indexs.length != 1) {
                throw new Exception("没有选择一个HOSTS文件");
            }
            String bakFilePathName = tableModel.getValueAt(indexs[0], 0).toString();
            String bakHost = FileUtil.readFile(bakFilePathName);
            TextArea_Bak.setText(bakHost);
        } catch (Exception ex) {
            //Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Button_Bak_ViewActionPerformed

    private void Button_BakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_BakActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel tableModel = (DefaultTableModel) Table_Bak.getModel();
            int[] indexs = Table_Bak.getSelectedRows();
            if (indexs.length != 1) {
                throw new Exception("没有选择一个HOSTS文件");
            }
            String bakFilePathName = tableModel.getValueAt(indexs[0], 0).toString();
            FileUtil.copyFileToHost(bakFilePathName);
            JOptionPane.showMessageDialog(rootPane, "hosts文件已还原！", "提示信息", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            //Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Button_BakActionPerformed

    private void Button_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_UpdateActionPerformed
        try {
            // TODO add your handling code here:


            //更新
            String netHosts = TextArea_Net.getText().toString();

            if (netHosts == null || "".equals(netHosts)) {
                JOptionPane.showMessageDialog(rootPane, "请先获取网络上的Hosts", "异常信息", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //备份
            String hostPathName = OSUtil.getInstance().getHostsFilePathName();
            String bakFilePathName = FileUtil.copyFileToBak(hostPathName);
            //写入hosts文件
            FileUtil.writeFile(netHosts, OSUtil.getInstance().getHostsFilePathName());

            JOptionPane.showMessageDialog(rootPane, "hosts文件更新完成 原HOSTS备份为[" + bakFilePathName + "]！", "提示信息", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            //Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_Button_UpdateActionPerformed

    private void MenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemActionPerformed
        // TODO add your handling code here:

        Dialog_About.setModal(true);
        Dialog_About.pack();
        Dialog_About.setLocationRelativeTo(HostsTool.this);
        Dialog_About.setVisible(true);

    }//GEN-LAST:event_MenuItemActionPerformed

    private void ToggleButton_ThinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_ThinksActionPerformed
        // TODO add your handling code here:
        if (THINKS_TYPEB) {
            Panel_Help.setVisible(true);
            Panel_License.setVisible(false);
            Panel_Info.setVisible(false);
            THINKS_TYPEB = !THINKS_TYPEB;
            LICENSE_TYPEB = true;
            ToggleButton_License.setSelected(false);
        } else {
            Panel_Help.setVisible(false);
            Panel_License.setVisible(false);
            Panel_Info.setVisible(true);

            THINKS_TYPEB = !THINKS_TYPEB;
            LICENSE_TYPEB = true;
            ToggleButton_License.setSelected(false);
        }
    }//GEN-LAST:event_ToggleButton_ThinksActionPerformed

    private void ToggleButton_LicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_LicenseActionPerformed
        // TODO add your handling code here:
        if (LICENSE_TYPEB) {
            Panel_Help.setVisible(false);
            Panel_License.setVisible(true);
            Panel_Info.setVisible(false);
            LICENSE_TYPEB = !LICENSE_TYPEB;
            THINKS_TYPEB = true;
            ToggleButton_Thinks.setSelected(false);
        } else {
            Panel_Help.setVisible(false);
            Panel_License.setVisible(false);
            Panel_Info.setVisible(true);

            LICENSE_TYPEB = !LICENSE_TYPEB;
            THINKS_TYPEB = true;
            ToggleButton_Thinks.setSelected(false);
        }
    }//GEN-LAST:event_ToggleButton_LicenseActionPerformed

    private void Button_GetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_GetActionPerformed

        // TODO add your handling code here:

        Thread getNetHosThread = new Thread(new Runnable() {
            @Override
            public void run() {
                boolean gs = jCheckBox2.isSelected();
                boolean wk = jCheckBox3.isSelected();
                boolean twttr = jCheckBox5.isSelected();
                boolean fb = jCheckBox4.isSelected();
                boolean flkr = jCheckBox6.isSelected();
                boolean dpbx = jCheckBox7.isSelected();
                boolean odrv = jCheckBox8.isSelected();
                boolean yt = jCheckBox9.isSelected();
                boolean nohl = jCheckBox1.isSelected();

                try {
                    String netHosts = NetUtil.getInstance().getHtmlInfo(gs, wk, twttr, fb, flkr, dpbx, odrv, yt, nohl);
                    TextArea_Net.setText(netHosts);
                } catch (Exception ex) {
                    Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
                }


            }
        });

        getNetHosThread.start();


    }//GEN-LAST:event_Button_GetActionPerformed

    private void MenuItem_DNSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_DNSActionPerformed
        // TODO add your handling code here:
        String msg = OSUtil.getInstance().reSatrtNet();

        if (msg.indexOf(OSUtil.ERROR_STRING) != -1) {
            JOptionPane.showMessageDialog(rootPane, msg.substring(msg.indexOf(OSUtil.ERROR_STRING), msg.length()), "提示信息", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(rootPane, "刷新本地缓存成功！", "提示信息", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_MenuItem_DNSActionPerformed

    private void Button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveActionPerformed
        // TODO add your handling code here:
        String netHosts = TextArea_Net.getText().toString();

        if (netHosts == null || "".equals(netHosts)) {
            JOptionPane.showMessageDialog(rootPane, "请先获取网络上的Hosts", "异常信息", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // FileChooser_Save.setd
        //FileChooser_Save.setSelectedFile(new File("hosts" + DateUtil.getCopyTime()));

        try {
            if (JFileChooser.APPROVE_OPTION == FileChooser_Save.showSaveDialog(this)) {
                File selectFile = FileChooser_Save.getSelectedFile();
                if (selectFile.exists()) {
                    if (JOptionPane.YES_OPTION == JOptionPane.showConfirmDialog(this, "是否要覆盖[" + selectFile.getCanonicalPath() + "] ?", "保存", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)) {


                        FileUtil.writeFile(netHosts, selectFile.getCanonicalPath());
                        JOptionPane.showMessageDialog(rootPane, "保存hosts到[" + selectFile.getCanonicalPath() + "]成功！", "提示信息", JOptionPane.INFORMATION_MESSAGE);

                    } else {
                        Button_Save.doClick();
                        FileChooser_Save.setSelectedFile(new File(selectFile.getName()));
                    }
                } else {
                    FileUtil.writeFile(netHosts, selectFile.getCanonicalPath());
                    JOptionPane.showMessageDialog(rootPane, "保存hosts到[" + selectFile.getCanonicalPath() + "]成功！", "提示信息", JOptionPane.INFORMATION_MESSAGE);

                }
            }
        } catch (Exception ex) {
            //Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }
        FileChooser_Save.setSelectedFile(new File("hosts" + DateUtil.getCopyTime()));
    }//GEN-LAST:event_Button_SaveActionPerformed

    private void MenuItem_CopyMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_CopyMailActionPerformed
        try {
            // TODO add your handling code here:
            ClipboardUtil.saveTextOnClipboard(Label_Mail.getText().toString().trim());
            if (Label_Mail.getText().toString().trim().equals(ClipboardUtil.getTextFromClipboard())) {

                JOptionPane.showMessageDialog(this, "复制成功", "消息提示", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "复制失败", "消息提示", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_MenuItem_CopyMailActionPerformed

    private void MenuItem_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_OpenActionPerformed
        // TODO add your handling code here:
        try {
            new OpenHomePageUtil(Label_HomePage.getText().toString());
        } catch (Exception ex) {
            Logger.getLogger(HostsTool.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "异常信息", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MenuItem_OpenActionPerformed

    private void Label_MailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_MailMouseEntered
        // TODO add your handling code here:
        
        Label_Mail.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_Label_MailMouseEntered

    private void Label_MailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_MailMouseExited
        // TODO add your handling code here:
        Label_Mail.setForeground(java.awt.Color.green);
        
    }//GEN-LAST:event_Label_MailMouseExited

    private void Label_HomePageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_HomePageMouseEntered
        // TODO add your handling code here:
        Label_HomePage.setForeground(java.awt.Color.red);
    }//GEN-LAST:event_Label_HomePageMouseEntered

    private void Label_HomePageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_HomePageMouseExited
        // TODO add your handling code here:
        Label_HomePage.setForeground(java.awt.Color.cyan);
    }//GEN-LAST:event_Label_HomePageMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HostsTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HostsTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HostsTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HostsTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HostsTool().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Bak;
    private javax.swing.JButton Button_Bak_Update;
    private javax.swing.JButton Button_Bak_View;
    private javax.swing.JButton Button_Get;
    private javax.swing.JButton Button_Save;
    private javax.swing.JButton Button_Update;
    private javax.swing.JButton Button_View;
    private javax.swing.JDialog Dialog_About;
    private javax.swing.JFileChooser FileChooser_Save;
    private javax.swing.JLabel Label_About;
    private javax.swing.JLabel Label_Auther;
    private javax.swing.JLabel Label_CopyRight;
    private javax.swing.JLabel Label_Desc;
    private javax.swing.JLabel Label_Help;
    private javax.swing.JLabel Label_HomePage;
    private javax.swing.JLabel Label_License;
    private javax.swing.JLabel Label_Logo;
    private javax.swing.JLabel Label_Mail;
    private javax.swing.JLabel Label_Version;
    private javax.swing.JLabel Label_WARA;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenuItem MenuItem;
    private javax.swing.JMenuItem MenuItem_CopyMail;
    private javax.swing.JMenuItem MenuItem_DNS;
    private javax.swing.JMenuItem MenuItem_Open;
    private javax.swing.JMenu Menu_Tool;
    private javax.swing.JPanel Panel_About;
    private javax.swing.JPanel Panel_Bak;
    private javax.swing.JPanel Panel_Help;
    private javax.swing.JPanel Panel_Info;
    private javax.swing.JPanel Panel_License;
    private javax.swing.JPanel Panel_Local;
    private javax.swing.JPanel Panel_Net;
    private javax.swing.JPanel Panel_Params;
    private javax.swing.JPopupMenu PopupMenu_CopyMail;
    private javax.swing.JPopupMenu PopupMenu_Open;
    private javax.swing.JScrollPane ScrollPane_Bak_Table;
    private javax.swing.JScrollPane ScrollPane_Bak_TextArea;
    private javax.swing.JScrollPane ScrollPane_Help;
    private javax.swing.JScrollPane ScrollPane_License;
    private javax.swing.JScrollPane ScrollPane_Local;
    private javax.swing.JScrollPane ScrollPane_Net;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable Table_Bak;
    private javax.swing.JTextArea TextArea_Bak;
    private javax.swing.JTextArea TextArea_Help;
    private javax.swing.JTextArea TextArea_License;
    private javax.swing.JTextArea TextArea_Local;
    private javax.swing.JTextArea TextArea_Net;
    private javax.swing.JToggleButton ToggleButton_License;
    private javax.swing.JToggleButton ToggleButton_Thinks;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
